name: FancyHelper
version: 2.5.2
main: org.YanPl.FancyHelper
api-version: '1.18'
depend: [ProtocolLib]
authors: [ baicaizhale , zip8919 ]
commands:
  fancyhelper:
    description: FancyHelper 主命令
    aliases: [cli, fancy]
permissions:
  fancyhelper.cli:
    description: 允许使用 FancyHelper CLI 模式
    default: op
  fancyhelper.reload:
    description: 允许重新加载 FancyHelper 配置
    default: op
