name: MineAgent
version: 1.1.6
main: org.YanPl.MineAgent
api-version: '1.18'
authors: [ baicaizhale ]
commands:
  mineagent:
    description: Main command for MineAgent
    aliases: [cli]
permissions:
  mineagent.cli:
    description: Allow player to enter/exit CLI Mode
    default: op
  mineagent.reload:
    description: Allow player to reload plugin
    default: op
