name: FancyHelper
version: 2.4.1
main: org.YanPl.FancyHelper
api-version: '1.18'
authors: [ baicaizhale ]
commands:
  fancyhelper:
    description: Main command for FancyHelper
    aliases: [cli, fancy]
permissions:
  fancyhelper.cli:
    description: Allow player to enter/exit CLI Mode
    default: op
  fancyhelper.reload:
    description: Allow player to reload plugin
    default: op
